version: '3.0'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017 
    volumes:
      - ./docker-compose-files:/docker-entrypoint-initdb.d 
    environment:
      MONGO_INITDB_DATABASE: chat 